# -*- coding: utf-8 -*-
"""Copy of section7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rzksyDYNfaYvL3G6HtDIuhcKyTOrxaGk
"""

# Commented out IPython magic to ensure Python compatibility.
# Install Pytorch & other libraries
# %pip install -qqq torch torchvision setuptools scikit-learn

# Install Hugging Face libraries
# %pip install  --upgrade datasets -qqq accelerate hf-transfer transformers

from huggingface_hub import login

login("number") #add token

from datasets import load_dataset

# Dataset id from huggingface.co/dataset
dataset_id = "burtenshaw/PleIAs_common_corpus_code_classification"

# Load raw dataset
dataset = load_dataset(dataset_id)

print(len(dataset["train"]))
print(dataset["train"][0])

from transformers import AutoTokenizer

# Model id to load the tokenizer
model_id = "answerdotai/ModernBERT-base"

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Tokenize helper function
def tokenize(batch):
    return tokenizer(batch['text'], padding=True, truncation=True, return_tensors="pt")

# Tokenize dataset
tokenized_dataset = dataset.map(tokenize, batched=True, remove_columns=["text"])

print(tokenized_dataset["train"].features.keys())
# dict_keys(['labels', 'input_ids', 'attention_mask'])

from transformers import AutoModelForSequenceClassification

# ✅ Build a CONSISTENT label space from both splits
all_labels = set(tokenized_dataset["train"]["labels"])
if "test" in tokenized_dataset:
    all_labels |= set(tokenized_dataset["test"]["labels"])
labels = sorted(list(all_labels))
num_labels = len(labels)

label2id = {label: i for i, label in enumerate(labels)}
id2label = {str(i): label for i, label in enumerate(labels)}

print("Label2id:", label2id)
print("Num labels:", num_labels)

# Download the model from huggingface.co/models
model = AutoModelForSequenceClassification.from_pretrained(
    model_id,
    num_labels=num_labels,
    label2id={str(k): v for k, v in label2id.items()},
    id2label={str(v): k for k, v in label2id.items()},
)

model = model.to("cuda")

import numpy as np
from sklearn.metrics import f1_score

# Metric helper method
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    score = f1_score(
        labels, predictions, average="weighted"
    )
    return {"f1": float(score) if score == 1 else score}

from huggingface_hub import HfFolder
from transformers import Trainer, TrainingArguments

# Define training args
training_args = TrainingArguments(
    output_dir="ModernBERT-code-classifier",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=5e-5,
    num_train_epochs=3, #changed from 5 to 3
    bf16=True,  # bfloat16 training
    optim="adamw_torch_fused",
    logging_strategy="steps",
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    push_to_hub=True,
    hub_strategy="every_save",
    hub_token=HfFolder.get_token(),
    report_to="wandb"
)

import torch
torch.cuda.empty_cache()

# ✅ New robust map_labels with NO -1 fallback — hard error instead
def map_labels(batch):
    new_labels = []
    for label in batch["labels"]:
        if label in label2id:
            new_labels.append(label2id[label])
        else:
            raise ValueError(f"Unknown label: {label}")
    return {"labels": new_labels}

# ✅ Apply to BOTH splits
tokenized_dataset["train"] = tokenized_dataset["train"].map(map_labels, batched=True)
if "test" in tokenized_dataset:
    tokenized_dataset["test"] = tokenized_dataset["test"].map(map_labels, batched=True)

print("Unique labels in train:", set(tokenized_dataset["train"]["labels"]))
if "test" in tokenized_dataset:
    print("Unique labels in test:", set(tokenized_dataset["test"]["labels"]))

# ✅ Debug sanity check
print(f"Num labels in mapping: {num_labels}")

limited_dataset = tokenized_dataset["train"].select(range(100))

# Create a Trainer instance
trainer = Trainer(
   model=model,
   args=training_args,
   train_dataset=limited_dataset,
   eval_dataset=tokenized_dataset["test"] if "test" in tokenized_dataset else None,
   compute_metrics=compute_metrics,
)

trainer.train()

# clear memory

import torch
torch.cuda.empty_cache()

# del trainer
# del model
# del limited_dataset

"""# Underfitting"""

# define a low learning rate
training_args.learning_rate = 1e-7

# Create a Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=limited_dataset,
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics,
)
trainer.train()

# clear memory

import torch
torch.cuda.empty_cache()

#del trainer
#del model
#
#"""# Just right! 🥣"""
#
## define a valid learning rate
training_args.learning_rate = 5e-5

# Create a Trainer instance
trainer = Trainer(
   model=model,
   args=training_args,
   train_dataset=limited_dataset,
   eval_dataset=tokenized_dataset["test"],
   compute_metrics=compute_metrics,
)
trainer.train()

"""# Inference"""

from transformers import pipeline

# load model from huggingface.co/models using our repository id
classifier = pipeline(
    task="text-classification",
    model="argilla/ModernBERT-domain-classifier",
    device=0,
)

sample = """def add_numbers(a, b):
    return a + b"""

classifier(sample)
